### ISSUE TITLE
What browsers are supported?

### ISSUE THREAD

**Issue by Aaron3** [mgcrea/angular-pull-to-refresh#2]
I've tested the demo in chrome / safari on an ipad and in chrome on android and none have functioned correctly.

**Comment by mgcrea** [comment]
http://embed.plnkr.co/C4dV0cvWxvrfR6y0uCxI/preview

Should be working with any browser supporting `overflow-scrolling:touch`.

It has been tested & is working on iOS6/iOS7 iPad/iPhone.

**Comment by PatrickHeneise** [comment]
@mgcrea Any luck getting this to work on Android? Tried on a Nexus 5, Android 4.4, but doesn't work (while working on Safari/iPhone).
