### ISSUE TITLE
Jumpy

### ISSUE THREAD

**Issue by PatrickHeneise** [mgcrea/angular-pull-to-refresh#6]
I've tried a few things but can't find a solution. The refresh works fine with a slow pull, but when pulling quickly it seems to be quite 'jumpy', seems the re-rendering of the template or $scope.apply causes this, but I can't figure it out. Any solution? Here's how it looks like for me http://cl.ly/Tsin

**Comment by fjordansilva** [comment]
+1

**Comment by manifestinteractive** [comment]
Noticed this too, seems to happen right at the switching point of when the scroll height is met... which makes sense that this seems to be related to the template switching.  On actually seems to happen on the very first switch over.  Repeated changes in template on same page visit does not jump.  Only first change in template once pull height is reached.
