### ISSUE TITLE
Small lists don't work

### ISSUE THREAD

**Issue by link0001** [mgcrea/angular-pull-to-refresh#7]
If I trim your list down to where the number of rows fit on a screen without scrolling, I can't activate your pull-to-refresh.    Eg...  have only 4 out of 52 states loaded.

**Comment by olivierbossel** [comment]
Same issue but I think it's come from the safari "viewport" overscroll no ?
Have you a workaround that is compatible with your directive ? Cause now when you scroll and you are to top of the list, the full viewport will scroll (and you see the grey background of safari...).
An idea ?
Thanks in advance, nice directive anyway !

**Comment by mgcrea** [comment]
You should use https://github.com/mgcrea/angular-overflow-scroll for that.

**Comment by link0001** [comment]
Can I get a plunker example of this.  I'm trying the 'angular-overflow-scroll' with the 'pull-to-refresh' on your example and it doesn't seem to work.  I must be doing something wrong.
